### ISSUE TITLE
Doesn't work on Ubuntu 18

### ISSUE THREAD

**Issue by Zarovzky** [otiai10/ocrserver#21]
I have a Ubuntu Server VM as I hate Docker, the machine is clean and created with the following commands:

#Install go
rm -r /temp && \
	mkdir /temp && \
	cd /temp && \
	wget https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz && \
	tar -xvf go1.13.7.linux-amd64.tar.gz && \
	mv go /usr/local && \
	cd / && \
	rm -r /temp && \
	export GOROOT=/usr/local/go && \
	export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

#Install libs 
#2 - Lib installation
apt-get install -y \
	tesseract-ocr-all \
	libtesseract-dev \
	imagemagick \
	libleptonica-dev \
	gcc

So when:
go get github.com/otiai10/ocrserver/... 

The following error is thrown:
![image](https://user-images.githubusercontent.com/11941881/74163266-65476c00-4c22-11ea-9af2-59f470a722a0.png)

PD:

1. Tesseract does work individually as I can use the command line to interact with it 
2. Go does work properly as I tested an hello world from git

**Comment by otiai10** [comment]
Please give me a Dockerfile in which the problem can be reproduced.

**Comment by Zarovzky** [comment]
g++ was missing from the system also, after `apt-get install g++` everything behaves as expected
