### ISSUE TITLE
docker  quick start ,whilelist isn't working!

### ISSUE THREAD

**Issue by wuxue107** [otiai10/ocrserver#24]
docker  quick start ,whilelist isn't working! 
this simple "https://ocr-example.herokuapp.com/" is well.
from docker pull image. do not working

**Comment by otiai10** [comment]
Thank you. Nice catch. I guess it's related to this issue https://github.com/otiai10/gosseract/issues/145
I'll update the docker image and let you know.

**Comment by otiai10** [comment]
Closed by f9ef881cb8fb1f20b0ca807af61b41a813a069d9
