### ISSUE TITLE
fail to run main.go

### ISSUE THREAD

**Issue by damn-at** [otiai10/ocrserver#26]
Hello

i get the following error when running the code:

# github.com/otiai10/gosseract/v2
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

#reprdocuceable every time

```
go env
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\BlackPearl\AppData\Local\go-build
set GOENV=C:\Users\BlackPearl\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\BlackPearl\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\BLACKP~1\AppData\Local\Temp\go-build118439850=/tmp/go-build -gno-record-gcc-switches

```
go version
```
go version go1.15.6 windows/amd64

```
tesseract --version
```
tesseract v4.0.0.20190314
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.2.0
 Found AVX2
 Found AVX
 Found SSE

**Comment by damn-at** [comment]
noticed that mingw installed 32 bit instead of 64... so this part is solved.

now the next issue:

go run main.go
# github.com/otiai10/gosseract/v2
tessbridge.cpp:5:10: fatal error: leptonica/allheaders.h: No such file or directory
 #include <leptonica/allheaders.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by otiai10** [comment]
Have leptonica installed
