### ISSUE TITLE
The OCR results on the local machine are not the same as your demo website.

### ISSUE THREAD

**Issue by leowilbur** [otiai10/ocrserver#27]
I try to read the image on my local machine, but the result is bad:
![image](https://user-images.githubusercontent.com/31638970/113831453-d4cad400-97b1-11eb-9aed-6c7a4044d194.png)
But it is perfect on your demo website:
![image](https://user-images.githubusercontent.com/31638970/113831582-f6c45680-97b1-11eb-876d-12f9d3deac7f.png)
I don't know why, did you use any trained model for that?

**Comment by otiai10** [comment]
I guess that's because they are using different tesseract version. let me check later

**Comment by otiai10** [comment]
@leowilbur
is it possible to give me that image to test?

**Comment by otiai10** [comment]
and tell me how you did setup your local server.

* Manually? `go get github.com/otiai10/ocrserver && PORT=xxxxx ocrserver`
* Docker image? `docker run otiai10/ocrserver`
* Docker compose? `docker-compose up`

**Comment by leowilbur** [comment]
Hi @otiai10 
I just run directly with the docker 
```
docker run -p 8080:8080 otiai10/ocrserver
```
and this is the image
![image](https://user-images.githubusercontent.com/31638970/119918144-1c8c0180-bf92-11eb-9e96-d00444e016b7.png)

**Comment by otiai10** [comment]
Thanks. I'll be able to take time for this

**Comment by otiai10** [comment]
Fixed auto-build & deploy connection with both Docker hub and Heroku, which means docker image on your local and ocr-example on Heroku will be synced hereafter.
