### ISSUE TITLE
server does not serve js/index.js

### ISSUE THREAD

**Issue by id0Sch** [otiai10/ocrserver#7]
missing assets folder, the example page does not work
![image](https://cloud.githubusercontent.com/assets/5864772/15658234/9a988576-26c2-11e6-92a9-022ffb427048.png)

also is it possible to expose the language to the ui?
thanks!

**Comment by otiai10** [comment]
Ref: https://github.com/otiai10/marmoset/commit/eb10b2f750ce4bb9d99671aa55f1000399032e41

**Comment by otiai10** [comment]
@id0Sch Thank you very much!

**Comment by otiai10** [comment]
@id0Sch 

> also is it possible to expose the language to the ui?

do you mean list of available languages of Tesseract-OCR?

**Comment by id0Sch** [comment]
i want to control the language of the image through the request.
and thanks for the quick response!

**Comment by otiai10** [comment]
ah... I got it. Let's create another issue for that 😉

**Comment by id0Sch** [comment]
Yeah sure I'll do it in a minute

On Tuesday, May 31, 2016, OCHIAI, Hiromu <notifications@github.com> wrote:

> ah... I got it. Let's create another issue for that 😉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/otiai10/ocrserver/issues/7#issuecomment-222625014>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFl9RHzT4aD3jGazVBaHgt6dJmiqtRxkks5qG_ILgaJpZM4IqB-E>
> .
>


-- 
Ido Schachter
Software developer
[image: ironSource] <http://www.ironsrc.com>

email ido.schachter@ironsrc.com
mobile +972-52-605-2282
fax +972-77-5448273
28 Lilienblum St., Tel Aviv
ironsrc.com <http://www.ironsrc.com>
[image: linkedin] <https://www.linkedin.com/company/ironsource> [image:
twitter] <https://twitter.com/ironsource> [image: facebook]
<https://www.facebook.com/ironSource> [image: googleplus]
<https://plus.google.com/+ironsrc>
This email (including any attachments) is for the sole use of the intended
recipient and may contain confidential information which may be protected
by legal privilege. If you are not the intended recipient, or the employee
or agent responsible for delivering it to the intended recipient, you are
hereby notified that any use, dissemination, distribution or copying of
this communication and/or its content is strictly prohibited. If you are
not the intended recipient, please immediately notify us by reply email or
by telephone, delete this email and destroy any copies. Thank you.
